compile:
	g++ -g -Wall main.cpp student.cpp instructor.cpp -o Project1
	g++ -o main student.cpp instructor.cpp main.cpp

run:
	./main instructors.txt students.txt
testrun:
	g++ -o main student.cpp instructor.cpp stu-main.cpp
	./main testinstructors.txt teststudents.txt


clean:
	rm main

